ipe:
  # page orientation (P=portrait, L=landscape)
  PDF_PAGE_ORIENTATION: "L"
  PDF_PAGE_FORMAT: "letter"
  PDF_CREATOR: "Departamento de Sistemas"
  PDF_AUTHOR: "Abraham Rafael Rico Moreno"

  # document unit of measure [pt=point, mm=millimeter, cm=centimeter, in=inch]
  PDF_UNIT: "mm"
  PDF_MARGIN_HEADER: "5"
  PDF_MARGIN_FOOTER: "15"
  PDF_MARGIN_TOP: "20"
  PDF_MARGIN_BOTTOM: "20"
  PDF_MARGIN_LEFT: "20"
  PDF_MARGIN_RIGHT: "20"

  PDF_FONT_NAME_MAIN: "helvetica"
  PDF_FONT_SIZE_MAIN: "10"
  PDF_FONT_NAME_DATA: "helvetica"
  PDF_FONT_SIZE_DATA: "8"
  PDF_FONT_MONOSPACED: "courier"

  # header title
  PDF_HEADER_TITLE: "Veranda"
  # header description string
  PDF_HEADER_STRING: "   Veranda\nhttp://www.sitioweb.net"
  # image logo
  PDF_HEADER_LOGO: "ipe.gif"
  # header logo image width [mm]
  PDF_HEADER_LOGO_WIDTH: 20
  # Ratio used to scale the images
  PDF_IMAGE_SCALE_RATIO: "4"
  # magnification factor for titles
  HEAD_MAGNIFICATION: "1.1"
  # height of cell repect font height
  K_CELL_HEIGHT_RATIO: "1.25"
  # title magnification respect main font size
  K_TITLE_MAGNIFICATION: "1.3"
  # reduction factor for small font
  K_SMALL_RATIO: "2/3"

##################################DON'T TOUCH###################################

  # Disable default TCPDF default config
  K_TCPDF_EXTERNAL_CONFIG: true

  # Auto-detected parameters (leave empty for auto-detection)
  K_PATH_MAIN:
  K_PATH_URL:
  K_PATH_FONTS:
  K_PATH_CACHE:
  K_PATH_URL_CACHE:
  K_PATH_IMAGES: <?php echo sfConfig::get('sf_app_template_dir') . "/images/" . "\n" ?>
  K_BLANK_IMAGE: