prod:
  .settings:
    no_script_name:         true
    logging_enabled:        true

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            a75f982331bf8f5636e33e26d82ac1392ee6df08

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    enabled_modules:      [default,sfTCPDF, sfGuardGroup, sfGuardUser, sfGuardPermission, sfGuardAuth,sfGuardForgotPassword, sfGuardRegister]

    login_module:           sfGuardAuth
    login_action:           signin

    secure_module:          sfGuardAuth
    secure_action:          secure

    check_lock:             true

    charset:                utf-8
    i18n:                   true
    default_culture:        es

  .actions:
    login_module:    sfGuardAuth
    login_action:    signin