generator:
  class: sfPropelGenerator
  param:
    model_class:           Cliente
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Cliente
    plural:                Clientes
    route_prefix:          cliente
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        nombre_razon_social: { label: Razón Social }
        direccion: { label: Dirección }
        telefono: { label: Teléfono }
        direccion: { label: Dirección }
        cp: { label: Código Postal }
        telefono_extension: { label: Ext }
      list:
        title: Catalogo de clientes
        display: [nombre_razon_social, contacto, direccion,numero_ext_int,  colonia, cp, telefono,telefono_extension, celular, correo_empresarial, correo_personal ]
      filter:
        display: [nombre_razon_social, contacto, calle, colonia, telefono, celular, correo_empresarial, correo_personal ]
      form:    ~
      edit:    ~
      new:     
        title: Nuevo cliente
